### ISSUE TITLE
Hashrat always returns exit code 1 when used for something else than checking hashes

### ISSUE THREAD

**Issue by segfault3** [ColumPaget/Hashrat#1]
For example: 

```
hashrat /bin/ls; echo $?
```

returns

```
hash=[...]
1
```

This is because `result` is only set in `case ACT_CHECK` in [main.c#L137](https://github.com/ColumPaget/Hashrat/blob/6c294b2661552bfcaf683962c9218644d5a1f99d/main.c#L137-L138) and [at the end of main.c](https://github.com/ColumPaget/Hashrat/blob/6c294b2661552bfcaf683962c9218644d5a1f99d/main.c#L225-L226) it exits with 1 if `result` is False.

**Comment by ColumPaget** [comment]
Thanks for finding this. It must be that on my system the variable
defaults to zero, and so this doesn't happen.

I'll update it in the next release.

Colum

**Comment by segfault3** [comment]
I'd still like to see this fixed.

**Comment by ColumPaget** [comment]
I've just come by and spotted that this issue is still open. I thought I'd fixed it, but reading it now I realize that I totally misunderstood what you were saying and 'fixed' something else. I thought it was just a problem with the final exit code from the program, (hence my comment about an integer not being initialized) but the real problem is that many of the operations hashrat can do _don't return an exit code at all_. Historically I've been more interested in the text output of the program, and never considered the exit codes. 

I'm going to close this issue now because this time (version 1.8.3) I really think I've fixed it! Thanks for pointing it out to me. Sorry it took so long for me to realize what you were saying.
